services:
  mysql:
    image: mysql:9.1
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sushi
      MYSQL_DATABASE: gym
      MYSQL_USER: noir
      MYSQL_PASSWORD: sushi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    mem_limit: 500M

volumes:
  mysql_data: